
name: On PR Submit

# Control when the action will run.
on:
  # Trigger the workflow on push event
  pull_request:
    branches: [ main, master, develop, deployment ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Skip based on commit message
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build the docker image
      - run: |
          docker build \
            --no-cache \
            --file Dockerfile.for-ci .
